---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: concourse-demo
  - name: version

outputs:
  - name: build

run:
  path: concourse-demo/ci/tasks/build.sh
  args: [
    --input-dir, concourse-demo,
    --output-dir, build,
    --version-file, version/number,
    --artifactId, concourse-demo,
    --packaging, jar
  ]
