---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: concourse-demo

run:
  path: concourse-demo/ci/tasks/unit.sh
  args: [
    --input-dir, concourse-demo
  ]
