---
resources:
  - name: pcfdemo
    type: git
    source:
      uri: {{github-uri}}
      branch: {{github-branch}}

  - name: version
    type: semver
    source:
      bucket: {{s3-bucket-version}}
      initial_version: 1.0.0-rc.0
      key: current-version
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      region_name: {{s3-region-name}}
      endpoint: {{s3-endpoint}}

  - name: candidate-release
    type: s3
    source:
      bucket: {{s3-bucket-release-candidates}}
      regexp: pcfdemo-(.*).war
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      region_name: {{s3-region-name}}
      endpoint: {{s3-endpoint}}

jobs:
  - name: unit-test
    public: true
    plan:
      - get: pcfdemo
        trigger: true
      - task: unit
        file: pcfdemo/ci/tasks/unit.yml
        params: &MAVENPARAMS
          MAVEN_OPTS: {{maven-opts}}
          MAVEN_CONFIG: {{maven-config}}

  - name: build-artifact
    serial_groups: [ version ]
    plan:
      - get: pcfdemo
        passed: [ unit-test ]
        trigger: true
      - get: version
        params: { pre: rc }
      - task: build
        file: pcfdemo/ci/tasks/build.yml
        params:
          <<: *MAVENPARAMS
      - put: candidate-release
        params: { from: build/pcf-demo-(.*).war }
      - put: version
        params: { file: version/number }


  - name: major
    serial_groups: [ version ]
    plan:
      - put: version
        params: { bump: major, pre: rc }

  - name: minor
    serial_groups: [ version ]
    plan:
      - put: version
        params: { bump: minor, pre: rc }
